name: Node.js CI

on:
  push:
    branches: [master, feat/chfo/210409_ga]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Builds on many platforms

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: |
          npm install
          npm run package
