name: Continuous Delivery

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    name: Runs unit tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Do git checkout
      - uses: actions/checkout@v2

      # Build using node 12.x
      - name: Use node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      # Run unit tests 
      - name: Run unit tests
        run: |
          npm install
          npm run test


  build:
    name: Builds on many platforms
    needs: [unit-tests]

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform}}

    steps:
      - uses: actions/checkout@v2
      - name: Use node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Package for this platform
        run: |
          npm install
          npm run package


      - name: Make directory for artifact
        run: |
          mkdir artifacts

      - name: Gather artifacts on ubuntu
        if: (matrix.platform == 'ubuntu-latest')
        run: |
          cp -R hello-electron-linux-x64 artifacts/

      - name: Gather artifacts on macos
        if: (matrix.platform == 'macos-latest')
        run: |
          echo "skip cp -R hello-electron-darwin-x64 artifacts/ since it needs to be signed, anyway"

      - name: Gather artifacts on windows
        if: (matrix.platform == 'windows-latest')
        run: |
          cp -R hello-electron-win32-x64 artifacts/

      - uses: actions/upload-artifact@master
        with:
          name: hello-electron-${{ github.workflow }}-${{ matrix.platform }}
          path: artifacts
